import type {
  EnergyProjectAnalysisMetadataDto,
  EnergyProjectAnalysisSnapshotDto,
} from "../../../lib/config-api";

export function ngeeAnnGoldenSnapshot(input: {
  dataStatus?: "complete" | "partial" | "unavailable";
  coveragePct?: number;
  validIntervalCount?: number;
  expectedMeterIntervalCount?: number;
  lastSeenAt?: string | null;
  costAvailable?: boolean;
  levelFactsAvailable?: boolean;
} = {}): EnergyProjectAnalysisSnapshotDto {
  const dataStatus = input.dataStatus ?? "complete";
  const coveragePct = input.coveragePct ?? (dataStatus === "complete" ? 100 : dataStatus === "partial" ? 50 : 0);
  const expectedMeterIntervalCount = input.expectedMeterIntervalCount ?? 2_688;
  const validIntervalCount = input.validIntervalCount
    ?? (dataStatus === "complete" ? expectedMeterIntervalCount : dataStatus === "partial" ? 1_344 : 0);
  const lastSeenAt = input.lastSeenAt === undefined ? "2026-06-17T15:45:00.000Z" : input.lastSeenAt;
  const metadata = missingMetadata();
  const queryIds = [
    "scope_summary_v1",
    "hourly_profile_v1",
    "meter_breakdown_v1",
    "previous_meter_usage_v1",
    "operational_policy_scope_intervals_v1",
    "operational_policy_meter_intervals_v1",
  ] as const;
  const categoryDataHealth = {
    coveragePct: 100,
    expectedMeterIntervalCount: 1_344,
    validIntervalCount: 1_344,
    qualityEventCount: 0,
  };
  const circuitDataHealth = {
    coveragePct: 100,
    expectedMeterIntervalCount: 672,
    validIntervalCount: 672,
    qualityEventCount: 0,
  };
  const topCircuits: EnergyProjectAnalysisSnapshotDto["analysis"]["topCircuits"] = [
    {
      meterNodeId: "mapping-lvl-7-office-load-4-l1p22-l3p25-fan-isol1-2-16",
      name: "Office Load 4 Fan ISOL 1/2",
      appliance: "Fan ISOL 1/2",
      category: "load",
      meterRole: "component",
      usageKwh: 439.0972,
      sharePct: 28.6773,
      peakKw: 3.5307,
      qualityEventCount: 0,
      scopeId: "l7-load-4",
      parentScopeId: "level-7",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 247.9813, changeKwh: 191.1159, changePct: 77.0687 },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-7-office-load-3-l1p16-l3p21-15",
      name: "Office Load 3",
      appliance: "Office Load 3",
      category: "load",
      meterRole: "component",
      usageKwh: 337.9023,
      sharePct: 22.0683,
      peakKw: 3.017,
      qualityEventCount: 0,
      scopeId: "l7-load-3",
      parentScopeId: "level-7",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 337.9023, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-office-load-4-l1p19-l3p24-6",
      name: "Lvl 6 Office Load 4: L1P19-L3P24",
      appliance: "Office Load 4",
      category: "load",
      meterRole: "component",
      usageKwh: 255.1539,
      sharePct: 16.664,
      peakKw: 2.2782,
      qualityEventCount: 0,
      scopeId: "l6-load-4",
      parentScopeId: "level-6",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 255.1539, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-7-front-row-office-light-11",
      name: "Front Row Office Light",
      appliance: "Office Light",
      category: "light",
      meterRole: "component",
      usageKwh: 107.02,
      sharePct: 6.9894,
      peakKw: 0.9555,
      qualityEventCount: 0,
      scopeId: "l7-front-light",
      parentScopeId: "level-7",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 107.02, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-office-light-right-internal-2",
      name: "Lvl 6 Office Light-Right: Internal",
      appliance: "Office Light",
      category: "light",
      meterRole: "component",
      usageKwh: 70.6873,
      sharePct: 4.6166,
      peakKw: 0.6311,
      qualityEventCount: 0,
      scopeId: "l6-light-right",
      parentScopeId: "level-6",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 70.6873, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-7-office-load-2-l1p7-l3p15-14",
      name: "Office Load 2",
      appliance: "Office Load 2",
      category: "load",
      meterRole: "component",
      usageKwh: 66.1682,
      sharePct: 4.3214,
      peakKw: 0.5908,
      qualityEventCount: 0,
      scopeId: "l7-load-2",
      parentScopeId: "level-7",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 66.1682, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-7-back-row-office-light-10",
      name: "Back Row Office Light",
      appliance: "Office Light",
      category: "light",
      meterRole: "component",
      usageKwh: 48.9043,
      sharePct: 3.1939,
      peakKw: 0.4366,
      qualityEventCount: 0,
      scopeId: "l7-back-light",
      parentScopeId: "level-7",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 48.9043, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-office-load-5-l1p25-l3p29-fan-isol-1-2-7",
      name: "Lvl 6 Office Load 5: L1P25-L3P29 Fan Isol 1/2",
      appliance: "Fan Isol 1/2",
      category: "load",
      meterRole: "component",
      usageKwh: 42.3355,
      sharePct: 2.7649,
      peakKw: 0.378,
      qualityEventCount: 0,
      scopeId: "l6-load-5",
      parentScopeId: "level-6",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 42.3355, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-office-light-left-external-1",
      name: "Lvl 6 Office Light-Left: External",
      appliance: "Office Light",
      category: "light",
      meterRole: "component",
      usageKwh: 40.2871,
      sharePct: 2.6311,
      peakKw: 0.3597,
      qualityEventCount: 0,
      scopeId: "l6-light-left",
      parentScopeId: "level-6",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 40.2871, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-office-load-2-l1p7-l3p12-4",
      name: "Lvl 6 Office Load 2: L1P7-L3P12",
      appliance: "Office Load 2",
      category: "load",
      meterRole: "component",
      usageKwh: 37.4839,
      sharePct: 2.4481,
      peakKw: 0.3347,
      qualityEventCount: 0,
      scopeId: "l6-load-2",
      parentScopeId: "level-6",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 37.4839, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-7-office-load-1-l1p1-l3p6-13",
      name: "Office Load 1",
      appliance: "Office Load 1",
      category: "load",
      meterRole: "component",
      usageKwh: 28.122,
      sharePct: 1.8366,
      peakKw: 0.2511,
      qualityEventCount: 0,
      scopeId: "l7-load-1",
      parentScopeId: "level-7",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 28.122, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-7-middle-row-office-light-12",
      name: "Middle Row Office Light",
      appliance: "Office Light",
      category: "light",
      meterRole: "component",
      usageKwh: 20.7678,
      sharePct: 1.3563,
      peakKw: 0.2,
      qualityEventCount: 0,
      scopeId: "l7-middle-light",
      parentScopeId: "level-7",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 20.7678, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-office-load-3-l1p13-l3p18-5",
      name: "Lvl 6 Office Load 3: L1P13-L3P18",
      appliance: "Office Load 3",
      category: "load",
      meterRole: "component",
      usageKwh: 13.5291,
      sharePct: 0.8836,
      peakKw: 0.2,
      qualityEventCount: 0,
      scopeId: "l6-load-3",
      parentScopeId: "level-6",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 13.5291, changePct: null },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-office-load-1-l1p1-l3p6-3",
      name: "Lvl 6 Office Load 1: L1P1-L3P6",
      appliance: "Office Load 1",
      category: "load",
      meterRole: "component",
      usageKwh: 11.5379,
      sharePct: 0.7535,
      peakKw: 0.2,
      qualityEventCount: 0,
      scopeId: "l6-load-1",
      parentScopeId: "level-6",
      includedInOfficialTotal: false,
      comparison: { usageKwh: 0, changeKwh: 11.5379, changePct: null },
      dataHealth: circuitDataHealth,
    },
  ];
  const designatedTotals: NonNullable<EnergyProjectAnalysisSnapshotDto["analysis"]["designatedTotals"]> = [
    {
      meterNodeId: "mapping-lvl-7-total-office-load-18",
      name: "Total Office Load",
      appliance: "Office Load",
      category: "load",
      meterRole: "total",
      usageKwh: 874.1282,
      sharePct: 57.089,
      peakKw: 0,
      qualityEventCount: 0,
      scopeId: "l7-total-load",
      parentScopeId: "level-7",
      includedInOfficialTotal: true,
      comparison: { usageKwh: 609.1505, changeKwh: 264.9777, changePct: 43.4995 },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-total-office-load-9",
      name: "Lvl 6 Total Office Load",
      appliance: "Office Load",
      category: "load",
      meterRole: "total",
      usageKwh: 365.2958,
      sharePct: 23.8573,
      peakKw: 0,
      qualityEventCount: 0,
      scopeId: "l6-total-load",
      parentScopeId: "level-6",
      includedInOfficialTotal: true,
      comparison: { usageKwh: 365.3477, changeKwh: -0.0519, changePct: -0.0142 },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-7-total-office-light-17",
      name: "Total Office Light",
      appliance: "Office Light",
      category: "light",
      meterRole: "total",
      usageKwh: 180.0563,
      sharePct: 11.7594,
      peakKw: 0,
      qualityEventCount: 0,
      scopeId: "l7-total-light",
      parentScopeId: "level-7",
      includedInOfficialTotal: true,
      comparison: { usageKwh: 125.4752, changeKwh: 54.5811, changePct: 43.4995 },
      dataHealth: circuitDataHealth,
    },
    {
      meterNodeId: "mapping-lvl-6-total-office-light-8",
      name: "Lvl 6 Total Office Light",
      appliance: "Office Light",
      category: "light",
      meterRole: "total",
      usageKwh: 111.6881,
      sharePct: 7.2943,
      peakKw: 0,
      qualityEventCount: 0,
      scopeId: "l6-total-light",
      parentScopeId: "level-6",
      includedInOfficialTotal: true,
      comparison: { usageKwh: 111.7039, changeKwh: -0.0159, changePct: -0.0142 },
      dataHealth: circuitDataHealth,
    },
  ];

  const analysis: EnergyProjectAnalysisSnapshotDto["analysis"] = {
    context: {
      userId: "user-1",
      workspaceId: "workspace-1",
      projectId: "ngee-ann-polytechnic",
      projectName: "Ngee Ann Polytechnic",
      scopeId: "project",
      scopeName: "Ngee Ann Polytechnic",
      scopeType: "project",
      resource: "electricity",
      timezone: "Asia/Singapore",
      from: "2026-06-09T16:00:00.000Z",
      to: "2026-06-16T16:00:00.000Z",
      endExclusive: true,
      period: "Custom",
      hierarchyRevisionId: "hierarchy-v6",
      meterMappingRevisionId: "mapping-v1",
      meterFormulaRevisionId: "formula-v1",
      dataSnapshotId: "snapshot-ngee-ann-golden",
      metricVersion: "metric-v1",
      businessCalendarVersion: "calendar-v1",
      tariffScheduleVersion: "tariff-v1",
      resolvedAt: "2026-08-04T00:00:00.000Z",
    },
    summary: {
      usageKwh: 1531.168324,
      averageDailyUsageKwh: 218.738332,
      peakKw: 20.673108,
      peakAt: "2026-06-16T06:00:00.000Z",
      validIntervalCount,
      qualityEventCount: 0,
    },
    hourlyProfile: [],
    comparison: {
      from: "2026-06-02T16:00:00.000Z",
      to: "2026-06-09T16:00:00.000Z",
      usageKwh: 1211.6773,
      changeKwh: 319.4911,
      changePct: 26.3677,
    },
    categories: [
      {
        category: "load",
        usageKwh: 1239.4239,
        sharePct: 80.9463,
        comparison: { usageKwh: 974.4981, changeKwh: 264.9258, changePct: 27.1859 },
        dataHealth: categoryDataHealth,
      },
      {
        category: "light",
        usageKwh: 291.7444,
        sharePct: 19.0537,
        comparison: { usageKwh: 237.1791, changeKwh: 54.5653, changePct: 23.0059 },
        dataHealth: categoryDataHealth,
      },
    ],
    childScopes: [
      {
        nodeId: "level-7",
        name: "Level 7",
        nodeType: "level",
        usageKwh: 1054.1845,
        sharePct: 68.8484,
        metadata: missingScopeMetadata("level-7", "Level 7", 1054.1845),
        ...(input.levelFactsAvailable === false ? {} : {
          comparison: {
            usageKwh: 734.6257,
            changeKwh: 319.5588,
            changePct: 43.4995,
          },
          dataHealth: {
            coveragePct: 100,
            expectedMeterIntervalCount: 1_344,
            validIntervalCount: 1_344,
            qualityEventCount: 0,
          },
        }),
      },
      {
        nodeId: "level-6",
        name: "Level 6",
        nodeType: "level",
        usageKwh: 476.9838,
        sharePct: 31.1516,
        metadata: missingScopeMetadata("level-6", "Level 6", 476.9838),
        ...(input.levelFactsAvailable === false ? {} : {
          comparison: {
            usageKwh: 477.0516,
            changeKwh: -0.0678,
            changePct: -0.0142,
          },
          dataHealth: {
            coveragePct: 100,
            expectedMeterIntervalCount: 1_344,
            validIntervalCount: 1_344,
            qualityEventCount: 0,
          },
        }),
      },
    ],
    circuits: [...designatedTotals, ...topCircuits],
    topCircuits,
    designatedTotals,
    componentReconciliation: {
      officialUsageKwh: 1531.168324,
      componentUsageKwh: 1518.99648,
      gapKwh: 12.171844,
      ratioPct: 99.20506166374952,
      officialMeterNodeIds: designatedTotals.map((circuit) => circuit.meterNodeId),
      componentMeterNodeIds: topCircuits.map((circuit) => circuit.meterNodeId),
    },
    virtualMeters: [],
    offHours: {
      status: "available",
      operatingKwh: 1_200,
      standbyKwh: 331.168324,
      usageKwh: 1531.168324,
      sharePct: 21.63,
      timezone: "Asia/Singapore",
      businessCalendarVersion: "calendar-v1",
    },
    cost: input.costAvailable === false
      ? {
        status: "unavailable",
        reason: { code: "TARIFF_VERSION_MISSING", message: "No effective Tariff covers the selected period." },
        tariffScheduleVersion: "tariff-v1",
      }
      : {
        status: "available",
        amount: 489.973864,
        currency: "SGD",
        tariffScheduleVersion: "tariff-v1",
        allocations: [{
          from: "2026-06-09T16:00:00.000Z",
          to: "2026-06-16T16:00:00.000Z",
          ratePerKwh: 0.32,
          usageKwh: 1531.168324,
          cost: 489.973864,
        }],
      },
    dataHealth: {
      status: dataStatus,
      coveragePct,
      expectedMeterIntervalCount,
      validIntervalCount,
      qualityEventCount: 0,
      cumulativeDeltaMismatchCount: 0,
      averageKwMismatchCount: 0,
      invalidIntervalDurationCount: 0,
      ...(lastSeenAt ? { lastSeenAt } : {}),
      importBatchIds: ["batch-1", "batch-2", "batch-3", "batch-4"],
    },
    units: {
      usage: "kWh",
      demand: "kW",
      intervalMinutes: 15,
      timezone: "Asia/Singapore",
    },
    attention: [{
      code: "PEAK_FOCUS",
      severity: "info",
      title: "Review the Level 7 contribution to the recorded peak",
      evidence: "The trusted Project result identifies Level 7 as the largest child Scope.",
      suggestedAction: "Open Level 7 in the Scope selector and verify its leading Circuits.",
    }],
    provenance: {
      dataSnapshotId: "snapshot-ngee-ann-golden",
      hierarchyRevisionId: "hierarchy-v6",
      meterMappingRevisionId: "mapping-v1",
      meterFormulaRevisionId: "formula-v1",
      metricVersion: "metric-v1",
      ruleRevisionIds: ["rule-v1"],
      aggregationRule: "designated_total",
      sourceView: "energy_scope_intervals",
      queryIds: [...queryIds],
    },
    metadata,
  };

  return {
    context: {
      ...analysis.context,
      primaryPeriod: {
        start: "2026-06-09T16:00:00.000Z",
        endExclusive: "2026-06-16T16:00:00.000Z",
      },
      projectReleaseId: "release-ngee-ann-golden",
    },
    projectRelease: {
      id: "release-ngee-ann-golden",
      source: "template-revision",
      projectId: "ngee-ann-polytechnic",
      templateRevisionId: "template-v1",
      templateRevisionSequence: 1,
      recipe: { id: "energy-scope-analysis", version: "1" },
      renderer: {
        key: "ngee-ann-overview",
        version: "1",
        contractVersion: "project-analysis-snapshot@1",
      },
      hierarchyRevisionId: "hierarchy-v6",
      meterMappingRevisionId: "mapping-v1",
      meterFormulaRevisionId: "formula-v1",
      metricRevisionIds: ["energy.total_usage_kwh@1"],
      ruleRevisionIds: ["rule-v1"],
      businessCalendarVersion: "calendar-v1",
      tariffScheduleVersion: "tariff-v1",
      publishedAt: "2026-08-04T00:00:00.000Z",
      document: { schema_version: 2, templates: [] },
      catalog: [],
    },
    recipe: { id: "energy-scope-analysis", version: "1" },
    renderer: {
      key: "ngee-ann-overview",
      version: "1",
      contractVersion: "project-analysis-snapshot@1",
    },
    dataQuality: analysis.dataHealth,
    evidence: [{
      id: "evidence:ngee-ann-golden:energy.total_usage_kwh@1",
      metricId: "energy.total_usage_kwh@1",
      queryIds: [...queryIds],
      queryReceiptId: "receipt-ngee-ann-golden",
    }],
    findings: analysis.attention,
    dataSnapshot: {
      id: "snapshot-ngee-ann-golden",
      importBatchIds: ["batch-1", "batch-2", "batch-3", "batch-4"],
      lastSeenAt,
    },
    metadata,
    analysis,
  };
}

function missingMetadata(): EnergyProjectAnalysisMetadataDto {
  return {
    status: "missing",
    hierarchyRevisionId: "hierarchy-v6",
    timezone: "Asia/Singapore",
    period: {
      start: "2026-06-09T16:00:00.000Z",
      endExclusive: "2026-06-16T16:00:00.000Z",
    },
    selectedScope: missingScopeMetadata("project", "Ngee Ann Polytechnic", 1531.168324),
    comparisonScopes: [],
    evidence: [],
  };
}

function missingScopeMetadata(
  scopeId: string,
  scopeName: string,
  usageKwh: number,
): EnergyProjectAnalysisMetadataDto["selectedScope"] {
  const missingValue = (unit: "m2" | "people") => ({
    status: "missing" as const,
    value: null,
    unit,
    reason: "not-configured" as const,
    guidance: `Configure ${unit === "m2" ? "area" : "headcount"} metadata.`,
    metadataRevisionIds: [],
    hierarchyRevisionIds: ["hierarchy-v6"],
    evidence: [],
  });
  const missingNormalisation = (
    metricId: "energy.usage_per_sqm" | "energy.usage_per_person",
    unit: "kWh/m2" | "kWh/person",
  ) => ({
    status: "missing" as const,
    metricId,
    value: null,
    unit,
    reason: "not-configured" as const,
    guidance: "Configure the required Scope metadata.",
    metadataRevisionIds: [],
    hierarchyRevisionIds: ["hierarchy-v6"],
    evidence: [],
  });
  return {
    scopeId,
    scopeName,
    usageKwh,
    status: "missing",
    area: missingValue("m2"),
    headcount: missingValue("people"),
    normalisations: {
      eui: missingNormalisation("energy.usage_per_sqm", "kWh/m2"),
      perPax: missingNormalisation("energy.usage_per_person", "kWh/person"),
    },
    evidence: [],
  };
}
